//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobsMegaChallenge.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid OrderId { get; set; }
        public string Size { get; set; }
        public string Crust { get; set; }
        public string First_Topping { get; set; }
        public string Second_Topping { get; set; }
        public string Third_Topping { get; set; }
        public string Fourth_Topping { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int Zip { get; set; }
        public string Phone { get; set; }
        public string Payment { get; set; }
        public bool Complete { get; set; }
    }
}
